---
ingress_nginx_chart_version: 4.10.1  # chart version points to app version 1.10.1
kiwix_serve_image_digest: sha256:ebf9b935eb1301661289ff0dc7a17c6406b0ef0602ff7ca1c9d9187dbae81abe  # digest points to app version 3.7.0
