---
homelab_network_name: homelab-cm
homelab_network_domain: homelab.cavcrosby.net
homelab_network_k8s_endpoint_vip: 192.168.0.6
homelab_network_subnet: 192.168.0.0/24
homelab_network_gateway_ipv4_addr: 192.168.0.1
homelab_network_subnet_mask: 255.255.255.0
homelab_network_lower_bound: 192.168.0.50
homelab_network_upper_bound: 192.168.0.254
vpn_network_clients:
  - pubkey: M22Z/H+1Fg4EOfn8xrjM7g2K6qchJa+d+SyszP7yGzI=
    address: 192.168.0.45/24
  - pubkey: jKADq3XliV2+u9pKqBaOYVc+FK3U0EKkJ2xwrkJ6dC0=
    address: 192.168.0.46/24
  - pubkey: MGi9HXdavU5tR/uj9TbRBxVd2VDebyLww8fOKnv/HiE=
    address: 192.168.0.47/24
  - pubkey: mR1PkypwAOR8QPs49O2D2yecpJTYxn9WmyKO7//R+mk=
    address: 192.168.0.48/24

gerald_homelab_network_interface_name: en0
gerald_wireguard_network_interface_name: wg0
gerald_wireguard_server_port: 9490
gerald_homelab_mac_addr: 3C:D9:2B:56:A5:4B
gerald_homelab_ipv4_addr: 192.168.0.2
gerald_homelab_wireguard_ipv4_addr: 192.168.0.3

kronk_idrac_homelab_mac_addr: 18:66:DA:6B:8D:0D
kronk_idrac_homelab_ipv4_addr: 192.168.0.4

kronk_homelab_network_interface_name: en0
kronk_homelab_network_bridge_interface_name: virbr0
kronk_homelab_mac_addr: 18:66:DA:6B:8D:0B
kronk_homelab_ipv4_addr: 192.168.0.5
